import { MetadataRoute } from 'next'
 
export default function sitemap(): MetadataRoute.Sitemap {
return [
  {
    url: 'https://onlyfansai.online/',
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: 1,
  },    
  { url: 'https://onlyfansai.online/nsfw-chat/anahsa-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/abby-lynn-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/abby-opel-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/abbyellison-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/abigaiil-morris-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/adison-briana-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/adriana-chechik-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/aeriel-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/aeries-steele-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/aflowerpatter-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/ahegahoe-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/aida-cortes-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alejandra-mercedes-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/aletta-ocean-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alex-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alexa-morgan-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alexa-pearl-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alexa-pond-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alexa-vin-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alexia-rae-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alexis-faye-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alibaby444-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alice-brookes-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alice-goodwin-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alice-will-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alice-wood-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/aline-faria-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alittlekay-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alkethadea-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/allecakes-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/allie_nsfw-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/allison-parker-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/ally-hardesty-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alvajay-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alyssa-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/alyssa-scott-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amanda-nicole-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amanda-paris-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amanda-trivizas-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amber-marie-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amber-quinn-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amber-rose-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amber-sonata-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/ambermg_vip-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amira-west-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amouredelavie-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amournath-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amy-nicole-moore-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amy-ridler-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },
{ url: 'https://onlyfansai.online/nsfw-chat/amysong99-nsfw', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.5, },

]
      }